# Generated by Django 4.1.6 on 2023-02-10 05:48

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='이름'),
        ),
    ]
